# -*- coding: utf-8 -*-
"""Негодаева Кеда

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oW39TvAjzLhAkVAJWTGaYqoHBS-4SecP
"""

a=5
b=int(input())
print(a*b)
print(b)

a=int(input())
b=int(input())
print((a+b)**2)

a=15
b=10
c=int(input())
print((a+b)/c)

a=int(input())
b=int(input())
print((a+b)**2)

a=int(input())
b=int(input())
c=int(input())
h=int(input())
print(a+b+c)
print(int(0.5*a*h))

a=int(input())
b=int(input())
print(((a**3 + 14)/5)*b)

a=int(input())
n=int(input())
print((a**2)//n)

a=input()
b=input()
print(int(float(a) // float(b)))
print(int(a) * int(b))
print(int(a) % int(b))

n=int(input())
days= n//86400
hours= (n-((n//86400)*86400))//3600
minutes=((n-((n//86400)*86400))-((hours*3600)))//60
print(days,':',hours,':',str(minutes))

n=int(input())
m=str(n)
print(n+int(m+m)+int(m+m+m))

for i in range(1000):
  print('1000-7')